language: java

addons:
  sonarcloud:
    organization: kiselica-aldin
    token:
      secure: PWtCTTZw4hqqh0kQdLTrozYSQ4JybABquf0/phr2BBMTaSrV0ssvEMNfBDjGC6aPY/bOBiGWJXMAVkpeiLMHXUr58G+FmBBwdt8hRq/4QUDC8yN+VThOoLgAfIUL2jV0gLrPAOLvuFi+IZ2bCclcfWgy90rBtVVKmPRCoS3jWWqV+gjGgn84JIOp94fxlZqMVJW69ca0m+52hSAYWBeqyiUoNX0gu+JI4pESoPoImA/V+bMYwJiHfcl9rjJFOM2b3jRncISsej7yFUieWq4dTd9ukr8FQqusDZavtI8PInEm3r6t+U2sQ6YzFKCzpq2P6Wewlf/1/sM4xtScXB87LxQ6sg5N5QvEIWQhLJTxgIx2ZmhjsNI987AifoTjrVppZBPgBZfs4ZaFph6FGOjvYMGKOZPbNQDYE4waOFNvCIHce54cFYvYAq7Dk8kp09CRwVs/J1uCWXPUrieksp5nDiKPXJL2xepK68e+A5PvNYeAFjXePGnYNqutcyDGRAqGkstOm2GqmKDNlwrcNtNfF9MNBuPoVe7SucNjw/X0+KA6N9kMXzkfFY7ctN6xg0MfzB+9Gg0djw06n47tCG8uetv+orLCOFUM9eThTumwQoTfqBFNDysDzGgfOtHblxDZTivZV8PAycxalW4aYqDrp81Hi4E/BeEfl0JPAz6uPF4=

script:
  - mvn clean verify sonar:sonar

cache:
  directories:
  - "$HOME/.sonar/cache"

env:
  global:
    secure: GNfCrsUi98zSAJVTUxY3I/RoQhz1R6XJVbbei0N3BLaH175X1oc/NZs4GbLH9D0UhblcYZZPojQNI/OPbM9J3scSKF94jeDuYKm63HcK65sUdaMsdKfJ6Vt+o/cttbjCBBFvqkapx13YpdCDcy1o/zK7BowyLz+Qh3SqoxjGuToK3UhhU56VSe9JXAZRzhZFGaToYumK0BDTsANYQZMpM9SdDpN9Fzdm1yNIfWJ7VqOYcntJRuzu5IUD9r6+R0kLLKGnRkf5Xc++F+w62s+PkEuMJ7tRQLQpPiB7EXbe1OM5+3sDg0ljo/xDHtCyjJchDSskvk4KG334LmvySEQor1rLygRkwkybX7CdwnpfJIacUKVQO6ZC5WmWVen0obsy4saYClEswVgkws9i4ws/QW3FNOeLQDHcJCdG8UA+LnM/NLuA2kT21nGSw8k8MpVO7OxYG9YM2N5hRww83lmkHM8/bGrKrW400MRsoH0Honxqup6/Emu4abxwuwhMTOZLeM2i2HWGXSPxO+sVu00fEqStxZFKXtdi3Hc67H+e1Th45hagLsPb2xB8X1P3i2RWm9oC8ZRE0/phYR3FI9HE6soIUBuG6tYWhkJDNPZK4YaFmB5puZh7HF3Qmtfhs9q3orNIWO1zdvNgGta2TGAC1ihixuy7D9t/a3tVO40pmTQ=
