language: java

addons:
  sonarcloud:
    organization: "kiselica-aldin"
    token:
      secure: "C3T2da7F1ZCf08ROihK46nuIECNmww86eTEUfEEz8GcEjJTv3bhw9eCPC9TgXgTqAL6gef2rqHtTfc4FMAgtzof381QBy2tUD93qamci8gFMZliazIT583H3uEeX+ST3h5MqNdX5wgm2O10rfvaD6irGMzHJDVDRtRdIqZrJFyur++cq1A3IBCB/7GdiO5vneUFVFKlIuLa/fLB5X06xY85iyd4IomS8UXF8ZzEU47BJvvBQZF08M8BgNgE0D6LQSGhNGqKDao3OqO6LptwatmVbtVovVUE6XCGJyxDPToaE3fIthi6BEMEwOul9oOlrQhc82HgBayF9dMU3+YCbDd0u/mJF18s98sWYU9/6I/Hzo+ICEfxb3fDg84WWgS9qVdwcV6WPMoexPoiwm7T2aZeyouxSHOKTksys72UyGVthrOAeWdxqWmD2B4pkAa6c85lQPYCR6H1W4aRN1gYpYVMU6V/i9ZUzOQlKNWkS+Yq9QWvDQXLqaz1iWzvXsoujVIYcb3xM/GnGct3iU0Z4NTFWXV44e+GqPDiq+IzH2ZJ1JsnwLpbM2KPP5ESb9u4tawCV+TvktWRCuLKtrNQpE4UwW/Gmm7sRg3ExWsOgthiru0G04yb827KiPTzZYos4WdSHnYXi4oJ+Iu7ROHIVuBvOZ6uDbT58lOgRV+5VItw="

script:
  - mvn clean verify sonar:sonar

cache:
  directories:
  - "$HOME/.sonar/cache"
