language: java

addons:
  sonarcloud:
    organization: "kiselica-aldin" # the key of the org you chose at step #3
    token:
      secure: "ZjMzYTJlNGZmOTYzNmU5ZDkxMGFhNzJkOTExYjhiYWM4NjhlNDc0NA==" # encrypted value of your token

script:
  - ./mvnw clean install

after_success:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
