language: java

addons:
  sonarcloud:
    organization: "kiselica-aldin"

script:
  - mvn clean verify sonar:sonar

after_success:
  - mvn clean test jacoco:report cobertura:cobertura coveralls:report -X

cache:
  directories:
  - "$HOME/.sonar/cache"
