language: java

addons:
  sonarcloud:
    organization: "kiselica-aldin" # the key of the org you chose at step #3

script:
  - ./mvnw clean install

after_success:
  - mvn sonar:sonar

cache:
  directories:
    - '$HOME/.sonar/cache'
